version: '3.8'

services:
  kustomize-builder-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: newrahmat/kustomize-builder
    container_name: kustomize-builder-dev
    ports:
      - "5000:5000"
      - "5678:5678"  # For debugging
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    # volumes:
    #   # Mount source code for hot reloading
    #   - .:/app
    #   # Mount samples directory for persistent storage
    #   - ./samples:/app/samples:ro
    #   # Mount logs directory
    #   - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - kustomize-network-dev
    labels:
      - "com.docker.compose.service=kustomize-builder-dev"
      - "com.docker.compose.project=kustomize-builder-dev"
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]

  # Development database (if needed in future)
  # redis:
  #   image: redis:alpine
  #   container_name: kustomize-builder-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - kustomize-network-dev

networks:
  kustomize-network-dev:
    driver: bridge
    name: kustomize-network-dev

# volumes:
  # redis_data:
  #   driver: local 