#!/bin/bash

# Example bash script generated by Kustomize Builder
# This script creates a kustomization.yaml file using EOF heredoc
# and then runs kustomize build

# Create directory
mkdir -p my-kustomization

# Create kustomization.yaml using EOF
cat > my-kustomization/kustomization.yaml << 'EOF'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: qoin
  repo: https://newrahmat.bitbucket.io
  releaseName: qoin
  namespace: admin
  version: 0.11.0
  valuesInline:
    name: qoin-be-client-manager
    port: 8086
    image:
      repo: loyaltolpi/qoin-be-client-manager
      tag: 2e6d963
    privateReg:
      enabled: true
    secretName: regcred
    selector:
      enabled: true
    nodeSelector:
      nodetype: front
EOF

# Run kustomize build
kustomize build --enable-helm my-kustomization 