#!/bin/bash

# Example helm template script generated by Kustomize Builder
# This script creates a kustomization.yaml file using EOF heredoc
# and then runs helm template with set arguments

# # Create directory
# mkdir -p my-kustomization

# # Create kustomization.yaml using EOF
# cat > my-kustomization/kustomization.yaml << 'EOF'
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# helmCharts:
# - name: qoin
#   repo: https://newrahmat.bitbucket.io
#   releaseName: qoin
#   namespace: admin
#   version: 0.11.0
#   valuesInline:
#     name: qoin-be-client-manager
#     port: 8086
#     image:
#       repo: loyaltolpi/qoin-be-client-manager
#       tag: 2e6d963
#     privateReg:
#       enabled: true
#     secretName: regcred
#     selector:
#       enabled: true
#     nodeSelector:
#       nodetype: front
# EOF

# Add helm repository
helm repo add loyaltolpi https://newrahmat.bitbucket.io

# Update helm repositories
helm repo update

# Run helm template with dynamic set arguments (extracted from valuesInline)
helm template loyaltolpi/qoin --set name=qoin-be-client-manager --set port=8086 --set image.repo=loyaltolpi/qoin-be-client-manager --set image.tag=2e6d963 --set privateReg.enabled=true --set secretName=regcred --set selector.enabled=true --set nodeSelector.nodetype=front 