apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: qoin
  repo: https://newrahmat.bitbucket.io
  releaseName: qoin
  namespace: admin
  version: 0.11.0
  valuesInline:
    name: qoin-be-client-manager
    port: 8086
# port2 is optional
    port2:
      enabled: false
    containerPort2: 9999
    namePort2: "grpc" 
# image repo and tag    
    image:
      repo: loyaltolpi/qoin-be-client-manager
      tag: 2e6d963
    # servicetype ClusterIP/NodePort
    servicetype: ClusterIP
# replicaCount is optional
    replicaCount: 1

# imagePullSecrets for private registry    
# kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
    privateReg:
      enabled: true
    secretName: regcred
 # if true enabled pod deploy by nodeSelector
 # nodetype front/back
    selector:
      enabled: true
    nodeSelector:
      nodetype: front 
    ##dotnet-v1###########
    # if true enabled dotnet with arg --environment
    arg:
      enabled: false
              # args:
              # - dotnet
              # - {{ .Values.name }}.dll
              # - --environment={{ .Values.env }}
    ##dotnet-v1###########

    ##dotnet-v2###########
    # if true enabled dotnet env variable
    envVar:
      enabled: false
    envName: "" 
    #manager/front 
    # envName: "ASPNETCORE_ENVIRONMENT" 
    #module/back 
    # envName: "DOTNET_ENVIRONMENT" 
              # env:
              # - name: {{ .Values.envName }}
              #   value: {{ .Values.env }}
    ##dotnet-v2###########

    # default tz Asia/Jakarta
    timezone:
      enabled: true
      path: /usr/share/zoneinfo/Asia/Jakarta
#fileConfig is optional volume mount secret file-config-volume from fileConfig.enabled=true
    fileConfig:
      enabled: false

    fileMount:
      enabled: false
    fileMountPath: "/"
    filesubPath: ".env"

    fileMount2:
      enabled: false
    fileMountPath2: "/"
    filesubPath2: ".app.config"
# dataSecret is optional volume mount secret data-secret-volume from dataSecret.enabled=true
    dataSecret:
      enabled: false
    fileBase64: "xxxxbase64xxxfilexxxxx"
    file2Base64: "xxxxbase64xxxfile2xxxxx"

